### ISSUE TITLE
how can I build iphone simulator

### ISSUE THREAD

**Issue by danransmile** [Fonta1n3/Tor-Connect#1]
<img width="571" alt="image" src="https://github.com/Fonta1n3/Tor-Connect/assets/15394628/97602e67-96e8-440b-917c-35321b4db1f7">

**Comment by Fonta1n3** [comment]
macOS only.

**Comment by danransmile** [comment]
I want to build with iphone simulator,can you help me ?

**Comment by Fonta1n3** [comment]
This is a macOS only app, closing the issue.
